# Generated by Django 5.1 on 2024-08-23 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='active',
        ),
        migrations.AddField(
            model_name='participation',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='is_conducting_raid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raid',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='raid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finalized', 'Finalized')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'raid')},
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.userprofile')),
            ],
            options={
                'unique_together': {('user', 'program')},
            },
        ),
    ]
