# Generated by Django 5.1 on 2024-08-23 23:21

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_manual_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('4-program', '4 Programs'), ('6-program', '6 Programs'), ('12-program', '12 Programs'), ('24-program', '24 Programs'), ('pvp', 'PvP')], max_length=50),
        ),
        migrations.CreateModel(
            name='PVPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_challenges_received', to='programs.userprofile')),
                ('challenged_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_challenges_received', to='programs.program')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_challenges_sent', to='programs.userprofile')),
                ('challenger_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_challenges_sent', to='programs.program')),
            ],
        ),
    ]
