# Generated by Django 5.1 on 2024-08-24 02:00

from django.db import migrations, models

def update_competition_types(apps, schema_editor):
    Competition = apps.get_model('programs', 'Competition')
    for competition in Competition.objects.all():
        if competition.competition_type == 'pvp':
            competition.competition_type = 'pvp'
            competition.save()

class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_manual_changes'),  # Replace with your actual previous migration
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('4-program', '4 Programs'), ('6-program', '6 Programs'), ('12-program', '12 Programs'), ('24-program', '24 Programs'), ('pvp', 'PvP')], max_length=50),
        ),
        migrations.RunPython(update_competition_types),
    ]
